<?php
// $Id$

function jsonrpc_server_server_info() {
  return array(
    '#name' => 'JSON-RPC',
    '#path' => 'json-rpc',
  );
}

function jsonrpc_server_server() {
  require_once('JsonRpcServer.php');
  $GLOBALS['devel_shutdown'] = false;
  $in = isset($_POST['method'])?$_POST:$_GET;
  $server = new JsonRpcServer($in);
  return $server->handle();
}

function jsonrpc_server_add_javascript() {
  static $added;
  if (!$added) {
    $path = drupal_get_path("module", "jsonrpc_server");
    drupal_add_js($path ."/jsonrpc_server.js");
    $added = true;
  }
}